### ISSUE TITLE
napi_hash_add is now static

### ISSUE THREAD

**Issue by mlosapio** [amzn/amzn-drivers#11]
Compilation error against 4.10 kernel

```
/root/rpmbuild/BUILD/ena-1.1.3/obj/default/kernel/linux/ena/ena_netdev.c:1493:3: error: implicit declaration of function 'napi_hash_add' [-Werror=implicit-function-declaration]
   napi_hash_add(&adapter->ena_napi[i].napi);
   ^
compilation terminated due to -Wfatal-errors.
cc1: some warnings being treated as errors
```

Possibly related to this: https://www.mail-archive.com/netdev@vger.kernel.org/msg136423.html

**Comment by mlosapio** [comment]
https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ena_netdev.c#L1493

**Comment by zorikm** [comment]
Thanks Michael for raising this.
We'll look into it and get back to you asap.
