### ISSUE TITLE
Running EFA on 4.12

### ISSUE THREAD

**Issue by kda88** [amzn/amzn-drivers#114]
Hi, 

I've loaded the module on 4.12 but I can't attach ib_ipoib device. 
How can I attach an address to the driver?

That't what I get:
[39435.059374] efa 0000:00:07.0: Setup irq:0xffff8f3bcee5b288 vector:93 name:efa-mgmnt@pci:0000:00:07.0
[39435.060730] infiniband efa_0: IB device registered

ip-172-30-4-150:~ # ibstat
CA 'efa_0'
 CA type: 
 Number of ports: 1
 Firmware version: 
 Hardware version: 
 Node GUID: 0x0000000000000000
 System image GUID: 0x0000000000000000
 Port 1:
 State: Active
 Physical state: LinkUp
 Rate: 100
 Base lid: 0
 LMC: 1
 SM lid: 0
 Capability mask: 0x00000000
 Port GUID: 0x100bf5fffe02e2b0
 Link layer: Unknown

loading ib_ipoib doesn't create an interface.

Thank you.

**Comment by galpress** [comment]
The EFA module does not support kernel verbs, hence cannot be used with any in-kernel ULPs such as IPoIB.
It can only be used with ib_uverbs at the moment.

**Comment by kda88** [comment]
Hi Gal,
Thanks for the info.

Could you please tell then the proper way to test the driver?
I haven’t found any info about that

Thank you!

**Comment by galpress** [comment]
Sure, more information can be found at:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html

Take a look at the "Getting Started with EFA" section for ways to test the driver.
