### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [amzn/amzn-drivers#118]
https://github.com/amzn/amzn-drivers/blob/0e97ea300b82d096108bb739428a4e4242b3ba77/kernel/linux/efa/efa_main.c#L448

**Comment by galpress** [comment]
Thanks for reporting this, will fix.

**Comment by galpress** [comment]
Issue resolved in: b0e5698437946d39bbec34b002496823855e3ee0
Thanks
