### ISSUE TITLE
XDP_REDIRECT Support

### ISSUE THREAD

**Issue by doonhammer** [amzn/amzn-drivers#128]
Is there a timeline for XDP_REDIRECT support ?

**Comment by gtzalik** [comment]
Hi @doonhammer,
We are currently working on adding XDP_REDIRECT to ENA driver. 
I can't share the timeline at this point but I will update here on our progress.

**Comment by doonhammer** [comment]
Thanks @gtzalik appreciate the update.

**Comment by talawahtech** [comment]
@gtzalik my understanding is that AF_XDP (one of the main targets of XDP_REDIRECT) support didn't make it into the Linux kernel until 4.18 or 4.19. Do you know if there are any plans to backport AF_XDP support to the 4.14 kernel used by Amazon Linux 2?

**Comment by akiyano** [comment]
@talawahtech There are currently no plans to backport AF_XDP support to the 4.14 AL2 kernel.

**Comment by washley** [comment]
Why was this closed? The backport question was not the issue, adding XDP_REDIRECT support is.

**Comment by akiyano** [comment]
@washley you are right, I'll leave it open for tracking and will close it once XDP_REDIRECT is released

**Comment by akiyano** [comment]
XDP_REDIRECT is currently expected to be released in Q4 of 2020

**Comment by doonhammer** [comment]
@akiyano thanks for the update.

Regards

John

**Comment by maryamtahhan** [comment]
Hey Folks

just wondering if this is still planned for Q4 2020? and in that case will it support redirect to AF_XDP sockets?

Thanks

**Comment by akiyano** [comment]
Hi @maryamtahhan,

XDP_REDIRECT will be in the next version we expect to release in the next few weeks.
It will also be submitted to the upstream Linux kernel at around the same time.

AF_XDP sockets support is planned for a future version.
I can't share the timeline at this point but I will update here on our progress.

Regards,
Arthur

**Comment by vcunat** [comment]
It's in 2.3.0 release notes: https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/RELEASENOTES.md#r230-release-notes

**Comment by akiyano** [comment]
@vcunat Yes you are correct XDP_REDIRECT was released as part of version 2.3.0
