### ISSUE TITLE
Interface attach issue

### ISSUE THREAD

**Issue by etherandrius** [amzn/amzn-drivers#162]
Hello, 

We have encountered a bug with the ENA driver. 
What happens is that the create and attach interface calls succeed, but the interface is never picked up by the host. 
```
00h 02m 10.251s(76962ms): [  131.671062] ena: reading reg failed for timeout. expected: req id[1] offset[88] actual: req id[57006] offset[0]
00h 02m 10.478s( 227ms): [  131.898167] ena: reading reg failed for timeout. expected: req id[2] offset[8] actual: req id[57007] offset[0]
00h 02m 10.529s(  51ms): [  131.912839] ena: Reg read32 timeout occurred
00h 02m 10.529s(   0ms): [  131.926173] ena 0000:00:04.0: Can not reset device
00h 02m 10.529s(   0ms): [  131.933268] ena 0000:00:04.0: ena device init failed
```

We believe that the function that times out is here 
https://github.com/amzn/amzn-drivers/blob/d6abd61df5ee1630b0e56a6847c3e9dd811e79a3/kernel/linux/common/ena_com/ena_com.c#L826-L886
specifically inside the for loop

**Comment by AWSNB** [comment]
You mind sending us the instance-id to zorik@amazon.com<mailto:zorik@amazon.com> and nafea@amazon.com<mailto:nafea@amazon.com> ?

What OS and ena driver version ?  ideally if you could share the full dmesg report would be great
