### ISSUE TITLE
ena_admin_aq_create_cq_cmd discrepancy

### ISSUE THREAD

**Issue by rzezeski** [amzn/amzn-drivers#194]
The `ena_admin_aq_create_cq_cmd` has the following comment:

```
	/* 4:0 : cq_entry_size_words - size of CQ entry in
	 *    32-bit words, valid values: 4, 8.
	 * 7:5 : reserved7
	 */
	u8 cq_caps_2;
```

However, the `ena_eth_io_tx_cdesc` is 64-bit (2 words), and `ena_eth_io_rx_cdesc_base` is 128-bit (4 words).

There is, of course, `ena_eth_io_rx_cdesc_ext`, which is 256-bit (8 words), but that's not currently used anywhere that I can see.

**Comment by davidarinzon** [comment]
Hi @rzezeski,
Thanks for identifying the inconsistency in the documentation. The valid values should be 2, 4 and 8. We will update the documentation in the future.
As you've also pointed out, currently 2 and 4 are used and 8 is not yet supported.
Let us know if you have additional questions.

**Comment by rzezeski** [comment]
@davidarinzon Awesome, thanks a bunch.
