### ISSUE TITLE
AF_XDP Support?

### ISSUE THREAD

**Issue by doonhammer** [amzn/amzn-drivers#197]
There have been discussions in the past about AF_XDP support and it sounded like it was "soon". Is there any update on the timeframe, even a rough date would help me a lot.

Regards

John

**Comment by davidarinzon** [comment]
Hi John,
Thank you for reaching out, we're planning of releasing the first version of AF_XDP support soon (😄), currently projecting JAN22 timeframe.
Feel free to reach out to me at darinzon@amazon.com for more details, I'll be happy to understand your use-cases and how you're planning to utilize AF_XDP.

Thanks,
David
