### ISSUE TITLE
DPDK 19.05 patches folder contains an duplicate/redundant patch

### ISSUE THREAD

**Issue by talawahtech** [amzn/amzn-drivers#199]
The folder of patches for DPDK 19.05 seems to contain a duplicate/redundant patch: `0004-net-ena-fix-L4-checksum-Tx-offload.patch`. This prevents `git am ../amzn-drivers/userspace/dpdk/19.05/*.patch` from applying the patches cleanly.

**Comment by shaibran** [comment]
@talawahtech  Thank you for notifying us, let us review this

**Comment by shaibran** [comment]
@talawahtech thank you. The file 0004-net-ena-fix-L4-checksum-Tx-offload.patch is indeed redundant and should be removed, for the moment, removing it should resolve the problem.
We noticed same issue also in:
userspace/dpdk/18.08/0019-net-ena-fix-L4-checksum-Tx-offload.patch
userspace/dpdk/18.11/0016-net-ena-fix-L4-checksum-Tx-offload.patch
userspace/dpdk/19.02/0006-net-ena-fix-L4-checksum-Tx-offload.patch
userspace/dpdk/19.05/0004-net-ena-fix-L4-checksum-Tx-offload.patch
we'll address all the above.
