### ISSUE TITLE
Add yum-utils to list of get-vfio-with-wc.sh dependencies

### ISSUE THREAD

**Issue by talawahtech** [amzn/amzn-drivers#201]
get-vfio-with-wc.sh installs a few dependencies (kernel-devel git make elfutils-libelf-devel patch) but I ran into an issue with one dependency that was not automatically installed. 

yumdownloader is used to [download the kernel sources](https://github.com/amzn/amzn-drivers/blob/d19387fef976787b4bfba626773aa7c8b49a1eb5/userspace/dpdk/enav2-vfio-patch/get-vfio-with-wc.sh#L58), but the required package (yum-utils) is not automatically installed. I ran into this issue trying to run  get-vfio-with-wc.sh on Fedora 34. Installing yum-utils manually resolved the issue.

**Comment by shaibran** [comment]
@talawahtech thanks, we have a fix ready and will publish it after regression tests
