### ISSUE TITLE
How to prepare a packet for transmission with DPDK

### ISSUE THREAD

**Issue by gshanemiller** [amzn/amzn-drivers#207]
DPDK can and cannot be faulted for its totally inadequate documentation of how to prepare a DPDK mbuf to TX over a DPDK TXQ on a vendor NIC. If one does not know already, don't go looking to DPDK to tell you. There are too many NICs with too much variation to step into that game. 

On the other hand the documentation also fails to point programmers to a direction to resolve this question even though this has got to be FAQ#2 after building.

Now in the case of AWS ENA NICs one might expect the DPDK doc to point to an Amazon PDF/HTTP URI which would answer this question. Is there such an animal?

I'll place this into context better:

* Programmers use this repo to among other things program DPDK AWS ENA NICs running over VFIO. We need good drivers. And Amazon surely delivers here!
* Programmers will create DPDK memory pool from which they get mbufs to hold packet data
* The mbuf has memory section --- a blob of memory of finite size --- into which the programmer needs to put any ethernet, IPv4 headers, and the payload. 
* Knowing what to put, and in what order must be supplied by vendors since its NIC H/W specific at least to a good approximation? There's probably some industry norms but I don't see Solarflare, Mellanox, and ENA NICs having the same profile.
* Here my vendor is AWS with its ENA NICs; I happen be working on `c5n` bare metal instances for what's worth

As best I can tell --- but I haven't quite gotten to running this code yet --- the memory layout conforms to this schema:

```
+-------------------------------------+ start of data room in mbuf
|+-----------------------------------+| packed, cache aligned address start of routing info 
|| Routing information w/ 3 fields   ||
|| dest mac address 6 bytes          ||
|| src  mac address 6 bytes          || 14 bytes total
|| eth type (0x800) 2 bytes          || 
|+-----------------------------------+| packed, cache aligned address start of IP packet header
|| IP packet header w/ 14 fields     || e.g. https://fab.cba.mit.edu/classes/961.04/people/neil/ip.pdf pg 3
||                                   || 
|| version 0x04     4  bits          ||
|| ihl              4  bits          ||
|| dscp             8  bits          ||
|| total length     16 bits          ||
|| id               16 bits          || 160 bits or 20 bytes
|| frag flags/offst 16 bits          ||
|| ttl              8  bits          ||
|| protocol         8  bits          ||
|| checksum         16 bits          ||
|| src address      32 bits          ||
|| dst address      32 bits          ||
|+-----------------------------------+| packet, cache aligned address start of UDP header
|| UDP packet header w/ 4 fields     ||
||                                   ||
|| src port         16 bits          ||
|| dst port         16 bits          ||
|| length           16 bits          ||
|| checksum         16 bits          || 
|+-----------------------------------+| cached aligned address of payload
|| data payload                      ||
|+-----------------------------------+|
+-------------------------------------+
```
Is there a smarter, better, official way to confirm this hopefully with field descriptions?

Let's keep DPDK + AWS better and smarter than the other guys!

**Comment by rodgarrison** [comment]
To help the community and toward improving DPDK-ENA integration I will provide a GIT url which among other things,

* Gives very clear build instructions of this, DPDK
* Gives very clear one time set up instructions of TLB 
* Provides a minimal-complete UDP client/server app on AWS-ENA NIC through DPDK
* Provides clear build instructions for former
* Provides the config for prev bullet clearly (hint 12-factor app ENV key/value pairs)
* Provides extended write up of the theory of mbuf packet preparation

The last point would be stronger if it was rejoined by an AWS publication/URI to confirm

**Comment by zorikm** [comment]
Rod, thank you so much for these insightful suggestions.
Please let us discuss and get back to you with our comments and conclusions.

**Comment by rodgarrison** [comment]
@zorikm No problem ... the least I can do is cary some water here. 

I want to mention in passing what perhaps is a the logical end of DPDK user space work ... something that's well beyond my expertise but may right up Amazon's engineering know-how to shoot-down OR contemplate elsewhere for the future.

If we're gonna go all user space NIC work ... how about we parlay this into any of the reduced-attack-service-uni-kernels and show up with something like:

https://news.ycombinator.com/item?id=30247022

plus DPDK user space apps ... it's got a as much kernel NIC stuff removed as makes sense. 

The DPDK library I'm working on is but 1/3rd of a larger distributed app. That app happens to align well with AWS graviton instances. A larger number of cores on cheaper HW makes it easier to have scalable user space NIC on a core that's colocated (as possible) with another core thread to which the DPDK lcore delegates. 

Packing the whole shebang into a smaller kernel ... maybe is a silly ask ... maybe makes sense eventually ... not sure.

**Comment by rodgarrison** [comment]
Apologies for long delay. Promised link:

https://github.com/rodgarrison/reinvent

**Comment by shaibran** [comment]
ENA currently implements only the generic DPDK PMD API, so any application which uses the API is not device specific but common to all devices.
Application writing is out of ENA team scope and knowledge. However, we do intend to enhance our documentation with detailed build instruction for all LTS and improve DPDK-ENA integration and ease of use so we will consider referencing your github from our best practices section or from a new section in the readme where we can reference application examples.
Thank you!
