### ISSUE TITLE
Is write-combining already enabled on Ubuntu 20.04.4 LTS with kernel 5.13.0-1021-aws?

### ISSUE THREAD

**Issue by techthumb** [amzn/amzn-drivers#215]
```
$ uname -r
5.13.0-1021-aws
```
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```
```
$ lspci -v -s 00:06.0
00:06.0 Ethernet controller: Amazon.com, Inc. Elastic Network Adapter (ENA)
	Physical Slot: 6
	Flags: fast devsel
	Memory at febf8000 (32-bit, non-prefetchable) [size=16K]
	Memory at fe900000 (32-bit, prefetchable) [size=1M]
	Memory at febe0000 (32-bit, non-prefetchable) [size=64K]
	Capabilities: [70] Express Endpoint, MSI 00
	Capabilities: [b0] MSI-X: Enable- Count=9 Masked-
	Kernel driver in use: vfio-pci
	Kernel modules: ena
```
```
$ cat /sys/kernel/debug/x86/pat_memtype_list | grep fe900000
PAT: [mem 0x00000000fe800000-0x00000000fe900000] write-combining
```

Questions:

1. Based on documentation at https://github.com/amzn/amzn-drivers/blob/master/userspace/dpdk/README.md#622-vfio-pci, is it okay to assume that `write-combining` is already enabled?
2. If the above is true, then, does one need to apply any of these patches for new/recent systems?

**Comment by shaibran** [comment]
Hey @techthumb [techthumb](https://github.com/techthumb), 
Yes, the BAR does seem to be mapped as WC as should.
Did you apply our patch for enabling vfio to work with WC?

**Comment by shaibran** [comment]
Hi @[techthumb](https://github.com/techthumb), please note that the region isn't mapped as WC as:

1. The pat_memtype_list is showing that the address WC region starts from 0xfe800000 and ends at 0xfe900000
2. The region which must be mapped as WC must start from 0xfe900000
3. You still need to apply the patches as described in the documentation you referenced.

see example for valid mapping:
```
$ cat /sys/kernel/debug/x86/pat_memtype_list | grep fe900000
PAT: [mem 0x00000000fe800000-0x00000000fe900000] write-combining
PAT: [mem 0x00000000fe900000-0x00000000ff900000] write-combining
```

**Comment by techthumb** [comment]
Thanks @shaibran

I am running into errors outlined in #198 

Any chance that issue can be investigated?
