### ISSUE TITLE
Newer Linux distributions certified?

### ISSUE THREAD

**Issue by ecki** [amzn/amzn-drivers#226]
Is it planned to certify newer Linux distributions like ubuntu 20, 22, RHEL 8.x, 9.0 and sles 15 sp4? I see there are release notes entries for example for RHEL 8.6. If no future certifications are planned and all newer distributions are expected to work, maybe remove the versions completely or state “7+”?

**Comment by akiyano** [comment]
Hi @ecki, 

Yes, newer distributions are certified.
The release notes will be updated in one of the next releases.

Thanks,
Arthur
