### ISSUE TITLE
Support Dynamic Device Personalization (DDP)

### ISSUE THREAD

**Issue by loneizhao** [amzn/amzn-drivers#227]
My customer is asking if Amazon ENA support DDP,  if not , any plan to support it ? Thanks

https://www.intel.com/content/www/us/en/architecture-and-technology/ethernet/dynamic-device-personalization-brief.html

**Comment by davidarinzon** [comment]
Hi @loneizhao,

Thank you for providing the introduction link above.
Can you share some insights on the use-cases that the customer has with this functionality?

Thanks!

**Comment by davidarinzon** [comment]
@loneizhao 
Do you possibly have information on how the customer is planning to use the feature? What are the use-cases?
You're welcome to contact me via Email if you wish.

**Comment by davidarinzon** [comment]
Hi @loneizhao,
This feature is not planned to be supported by ENA at the moment.
Thanks.
