### ISSUE TITLE
release 2.7.3 builds a driver with version 2.7.2g using dkms

### ISSUE THREAD

**Issue by chuckfloyd** [amzn/amzn-drivers#228]
git log shows the correct SHA: commit 751ad864dbf9e0a90c934d9ab2cc097d5a993e66 (HEAD -> master, tag: ena_linux_2.7.3, origin/master, origin/HEAD)

But after building with dkms, the module reports 2.7.2g instead of 2.7.3g
 ```
# modinfo -F version /var/lib/dkms/amzn-drivers/2.7.3/5.4.167-1.el7.elrepo.x86_64/x86_64/module/ena.ko
2.7.2g
```

**Comment by chuckfloyd** [comment]
looks like DRV_MODULE_GEN_SUBMINOR didn't get incremented in ena_netdev.h

**Comment by davidarinzon** [comment]
Hi @chuckfloyd 

Thank you actively looking and identifying this issue.
We will fix it.

David
