### ISSUE TITLE
Update repo with all bugfixes from in-kernel driver

### ISSUE THREAD

**Issue by dimaslv** [amzn/amzn-drivers#23]
According to https://github.com/torvalds/linux/commits/master/drivers/net/ethernet/amazon/ena driver has lot of bugfixes (including bugs we encounter) and version 1.1.7, rather this **official** repo of ena driver is still 1.1.3 and has no those fixes.

**Comment by yastreb78** [comment]
Dmitry,
We plan on updating this repo with version 1.2.0 very soon

**Comment by netanelbelgazal** [comment]
version 1.2.0 is out
