### ISSUE TITLE
Toeplitz hashing on C6i.metal

### ISSUE THREAD

**Issue by ashaffer** [amzn/amzn-drivers#233]
Hey guys,

I made a [thread](https://github.com/amzn/amzn-drivers/issues/109) a while back that you helped me with. I've recently attempted to switch serves to the C6i, and i've discovered that the toeplitz hash seems to be different yet again. I've obtained the hash key using `ethtool -x`:

```
    0x4b, 0x8c, 0xeb, 0xcb, 0x2a, 0xcc, 0xd6, 0xd0,
    0x8e, 0x12, 0xeb, 0x18, 0x46, 0xde, 0x8a, 0xea,
    0x72, 0x8e, 0xb5, 0x75, 0xb3, 0x8b, 0x7e, 0x11,
    0x4d, 0x21, 0x9e, 0xaf, 0x68, 0xaf, 0x84, 0x00,
    0xc6, 0xdc, 0x0c, 0x13, 0x11, 0x4a, 0x06, 0xe4
```

However, my computed RSS hashes don't seem to match what the ENA is generating. I've tried with an initial value of 0, an initial value of 0xFFFFFFFF (as the c5s require), and various alternative orderings of the relevant packet fields, and nothing seems to work.

**Comment by akiyano** [comment]
Hi @ashaffer,

Please read the "Configuring RSS" part in  https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst 
As well as the documentation inside the code of https://github.com/amzn/amzn-ec2-ena-utilities/blob/main/ena-toeplitz/toeplitz_calc.py

If that doesn't clear the issue up, please share with us:
All parameters needed for calculation of the hash: source and destination ips, ports and the exact output of ethtool -x.
Also what hash you expect to get (and how you calculated it) and what you actually got.
If you don't feel comfortable with posting this data here, you can write to me at akiyano@amazon.com
