### ISSUE TITLE
feature PTP Hardware Clock Support can't use in EC2

### ISSUE THREAD

**Issue by Noirwada** [amzn/amzn-drivers#250]
Hello 

I want to check this feature support from ena driver 2.8.0 version.
But i just test in m6i.large,m6i.metal,c5.metal with ` sudo ethtool -T eth0`

It will show 

```
Time stamping parameters for eth0:
Capabilities:
	software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
PTP Hardware Clock: none
Hardware Transmit Timestamp Modes: none
Hardware Receive Filter Modes: none
```

OS Version
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="[https://amazonlinux.com/ ](https://amazonlinux.com/)"
```
Kernel is updated to latest version

Is there only specific instance can support ? or should i setting the kernel configure and rebuild?

I can't find some material for step 

Thanks

**Comment by davidarinzon** [comment]
Hi @Noirwada 

The PTP Hardware Clock feature is currently not supported by AWS HW. Please stay tuned for AWS public announcements in the near future for enablement options.

**Comment by amitbern-aws** [comment]
AWS announcement: https://aws.amazon.com/blogs/compute/its-about-time-microsecond-accurate-clocks-on-amazon-ec2-instances/

Amazon Time Sync with microsecond-accurate time is available today in the Asia Pacific (Tokyo) Region on all R7g instances, and we will be expanding support to additional AWS Regions and EC2 Instance types.

**Comment by amitbern-aws** [comment]
Hi **@chris-kuhr**
Amazon Time Sync with microsecond-accurate time is currently available in US East (N. Virginia) and Asia Pacific (Tokyo) regions on all R7g instances. 
We don't have any information on Frankfurt (eu-central-1) at the moment but stay tuned for AWS public announcements in the future.
Thanks
