### ISSUE TITLE
Set static rss hash key in ena PMD driver

### ISSUE THREAD

**Issue by JasonJiang-VM** [amzn/amzn-drivers#267]
With DPDK 21.11, ena PMD driver version uses random dynamic rss hash key. It's not convenient for us to scale out our VPN traffic whose IPs are fixed already. With old 2.0.2 ena PMD driver, it uses a static rss hash key. We can use the https://github.com/amzn/amzn-ec2-ena-utilities/blob/main/ena-toeplitz/toeplitz_calc.py to choose the paired IPs for VPN tunnel.
After we upgrade to DPDK 21.11, with the random rss hash key, everything is broken. So we would like to set the original RSS hash key back to ena PMD driver like:  
``
ena_rss.c
 48 void ena_rss_key_fill(void *key, size_t size)
 49 {
 50 #if 0
 51         static bool key_generated;
 52         static uint8_t default_key[ENA_HASH_KEY_SIZE];
 53 #endif
 54         static uint8_t default_key[ENA_HASH_KEY_SIZE] = {
 55         0xbe, 0xac, 0x01, 0xfa, 0x6a, 0x42, 0xb7, 0x3b,
 56         0x80, 0x30, 0xf2, 0x0c, 0x77, 0xcb, 0x2d, 0xa3,
 57         0xae, 0x7b, 0x30, 0xb4, 0xd0, 0xca, 0x2b, 0xcb,
 58         0x43, 0xa3, 0x8f, 0xb0, 0x41, 0x67, 0x25, 0x3d,
 59         0x25, 0x5b, 0x0e, 0xc2, 0x6d, 0x5a, 0x56, 0xda
 60         };
 61 #if 0
 62         size_t i;
 63
 64         if (!key_generated) {
 65                 for (i = 0; i < RTE_DIM(default_key); ++i)
 66                         default_key[i] = rte_rand() & 0xff;
 67                 key_generated = true;
 68         }
 69 #endif
 70         RTE_ASSERT(size <= sizeof(default_key));
 71         rte_memcpy(key, default_key, RTE_MIN(size, sizeof(default_key)));
 72 }

But with the setting key, we still can't get the right rss queue mapping, for example: 
-bash-4.2$ ./toeplitz_calc.py -r 10.100.0.40 -R 0 -t 10.100.0.36 -T 0 -q 4
RSS queue index: 0
Peer RSS index: 1
But the rx queue number on two  hosts is: 3 and 1.
Local host:
RX_Q3_BYTES       : 134402
RX_Q3_CNT         : 857
 
peer host:
RX_Q1_BYTES       : 161536
RX_Q1_CNT         : 1061

What's wrong here? Please help. 
Thanks.

**Comment by shaibran** [comment]
let us review this and we'll update

**Comment by JasonJiang-VM** [comment]
Thanks for taking a look. Some update:
We tested the VPN traffic like: client VM-EDGE-VPN-EDGE-server VM, the traffic we are looking for is between the EDGE VPN tunnels, and the EDGE node is running on c5n.4xlarge EC2 instance, we get the hash value with [toeplitz_calc.py](https://github.com/amzn/amzn-ec2-ena-utilities/blob/main/ena-toeplitz/toeplitz_calc.py), modified the port number to 0 and init value to 0 instead of 0xffffffff. I tried to set with revert default key, but it is still not matching the real rss queue stats.
So please help to confirm how we can set a valid static RSS key and use the toeplitz_calc.py to get the real rss hash mapping. BTW, the real rss queue output seems consistent among reboots, so it seems the key doesn't change when doing reboot. 
Appreciate what you inputs.

Thanks
Jason

**Comment by shaibran** [comment]
Hi, the different features should be supported by both PMD (in DPDK21.11 it is 2.5.0) and by the device. Please see the RSS [section](https://github.com/amzn/amzn-drivers/blob/master/userspace/dpdk/README.md#11-rss-support) in our readme which covers this.
Note that calling `rte_eth_dev_rss_hash_update()` to set the hash fields can result with error/warning messages, so please review the logs to verify it is set as expected.
You can probe the supported hash functions from your app by using the API `rte_eth_dev_rss_hash_conf_get()` and reading the `.rss_hf` field in the structure `rte_eth_rss_conf`. Note that the method have different return codes depending on the support existence in the device.
Also note that script [toeplitz_calc.py](https://github.com/amzn/amzn-ec2-ena-utilities/tree/main/ena-toeplitz) covers specific ENA generations so its correctness depends on the instance type being used.

**Comment by JasonJiang-VM** [comment]
We set this on c5n.9xlarge and c5n.4xlarge, found it reports error:
2023-05-10T22:32:56.008Z perimeter-edge NSX 209189 FABRIC [nsx@6876 comp="nsx-edge" subcomp="datapathd" s2comp="intel-rte" level="WARN"] ena_rss_hash_set(): Setting RSS hash fields is not supported. Using default values: 0xc30

So we would like to know whether c5n.9xlarge and c5n.4xlarge supports to set rss key. If they doesn't support, what is the default key inside the device?  In past, we use the default key to verify the ipsec hash, it works with 2.0.2 ena PMD driver. But on the new driver 2.5.0, it is broken. So we are confused what changed. Please advice, thanks.

**Comment by shaibran** [comment]
Yes, this is the correct location where you can set your key

**Comment by JasonJiang-VM** [comment]
Sorry for keeping asking questions.  Another thing I would like to confirm is:
If I set the previous  default key:
be:ac:01:fa:6a:42:b7:3b:80:30:f2:0c:77:cb:2d:a3:ae:7b:30:b4:d0:ca:2b:cb:43:a3:8f:b0:41:67:25:3d:25:5b:0e:c2:6d:5a:56:da
do I need to revert it before setting in ena_rss_key_fill function if I use it in [toeplitz_calc.py](https://github.com/amzn/amzn-ec2-ena-utilities/tree/main/ena-toeplitz) script to calculate the rss hash?

Thanks

**Comment by shaibran** [comment]
No need, it is reverted by the ena driver

**Comment by shaibran** [comment]
Hi, sure.
Looks like the byte reorder is required to complete the key manipulation  in this case after all:

When user sets his key, it overrides the default randomly generated key. Then it is reordered so it arrives to the device in a reversed order to align to device requirements. In case it is being queried from the device it is reordered again.

When the user key set option is unsupported, as in this case, the driver uses the default randomly generated key with no byte reorder. Reversed or not, the key is a randomized one, and since in this mode it cannot be queried from the device anyway, there is no real point in reversing it and it is being set in its original byte order. 

Since the operation you attempted to perform is a manipulation of the regular driver flow, the key byte reorder step got missed since it is performed only on the arriving user key configuration and not on the default internal key. Sorry for misleading you on regarding the need to reorder it.
Need to explicitly reorder the your hacked RSS key bytes. Just add `ena_reorder_rss_hash_key `call inside `ena_rss_key_fill`.
i.e,
```
static void ena_com_hash_key_fill_default_key(struct ena_com_dev *ena_dev)
{
	uint8_t hw_rss_key[ENA_HASH_KEY_SIZE];
	static uint8_t default_key[ENA_HASH_KEY_SIZE] = {
	0xbe, 0xac, 0x01, 0xfa, 0x6a, 0x42, 0xb7, 0x3b,
	0x80, 0x30, 0xf2, 0x0c, 0x77, 0xcb, 0x2d, 0xa3,
	0xae, 0x7b, 0x30, 0xb4, 0xd0, 0xca, 0x2b, 0xcb,
	0x43, 0xa3, 0x8f, 0xb0, 0x41, 0x67, 0x25, 0x3d,
	0x25, 0x5b, 0x0e, 0xc2, 0x6d, 0x5a, 0x56, 0xda
	};

	ena_reorder_rss_hash_key(hw_rss_key, default_key, ENA_HASH_KEY_SIZE);

	struct ena_admin_feature_rss_flow_hash_control *hash_key =
		(ena_dev->rss).hash_key;

	/* skip randomized key generation
	 */
	 // ENA_RSS_FILL_KEY(&hash_key->key, sizeof(hash_key->key));

	/* The key buffer is stored in the device in an array of
	 * uint32 elements.
	 */
	memcpy(hash_key->key, hw_rss_key, ENA_HASH_KEY_SIZE);
	hash_key->key_parts = ENA_ADMIN_RSS_KEY_PARTS;
}
```

**Comment by shaibran** [comment]
@JasonJiang-VM did you attempt to reverse the key as explained in the code snippet above?

**Comment by JasonJiang-VM** [comment]
Thanks @shaibran. Today, I finished the testing, it works as expected. Appreciated your great supporting. We can close this issue now.

Thanks,
Jason
