### ISSUE TITLE
[Bug]: Why the switch of netdim adaptive-rx has no effect on performance on m6i.8xlarge

### ISSUE THREAD

**Issue by Heng-Qi** [amzn/amzn-drivers#272]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
- [X] I have followed the [AWS official troubleshoot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).
- [X] I have followed the driver [readme](https://github.com/amzn/amzn-drivers) and [best practices](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst).

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

6.1.34-58.102.amzn2023.x86_6

### Custom Code

No

### OS Platform and Distribution

6.1.34-58.102.amzn2023.x86_6

### Bug description

When I tested netdim adaptive rx on/off with sockperf\iperf3\nginx, I found that the switch of dim had no effect on the performance Bps, but the number of interrupts did drop. In the various scenarios I tested, I found no effect of dim. Excuse me, is there a suitable scenario to test the performance improvement brought by netdim?

### Reproduction steps

```bash
server: iperf3 -s -p 8989
client: iperf3 -c server_ip -t 10 -M 88 -p 5200 -p 8989

server: sockperf sr  --tcp
client: sockperf tp -i 172.16.1.166 -t 10 --tcp -m ${msg_size}

server: nginx (default in aws os)
client: wrk -c ${connections} -t 4 -d 10 http://server_ip
```

### Expected Behavior

Find out where aws netdim has a performance boost.

### Actual Behavior

aws netdim does not improve performance (throughput/latency).

### Contact Details

hengqi@linux.alibaba.com

**Comment by davidarinzon** [comment]
The customer has chosen to engage in direct email communication
