### ISSUE TITLE
[Support]: ENA upstream driver timeout - use this driver instead?

### ISSUE THREAD

**Issue by Vincinator** [amzn/amzn-drivers#277]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
- [X] I have followed the [AWS official troubleshoot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).
- [X] I have followed the driver [readme](https://github.com/amzn/amzn-drivers) and [best practices](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst).

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

upstream

### Custom Code

No

### OS Platform and Distribution

Linux 5.15.114 driver from [drivers/net/ethernet/amazon/ena](https://elixir.bootlin.com/linux/v5.15.114/source/drivers/net/ethernet/amazon/ena) 

### Support request

Hi, 

we encounter crashes of aws instances due to the ena driver from kernel mainline (5.15.114) having timeouts. 
It seems that not every instance is affected, which makes it complicated to debug.

We were able to receive the following dmesg log: 

```
[...]: ena 0000:00:05.0 ens5: The ena device didn't send a completion for the admin cmd 11 status 0
[...]: ena 0000:00:05.0 ens5: Failed to get stats. error: -62
[...]: ena 0000:00:05.0: Failed to get ENI stats
[...]: ena 0000:00:05.0 ens5: ENA admin queue is not in running state!
[...]: ena 0000:00:05.0 ens5: Trigger reset is on
[...]: ena 0000:00:05.0 ens5: tx_timeout: 0
[...]: ena 0000:00:05.0 ens5: suspend: 0
[...]: ena 0000:00:05.0 ens5: resume: 0
[...]: ena 0000:00:05.0 ens5: wd_expired: 0
[...]: ena 0000:00:05.0 ens5: interface_up: 2
[...]: ena 0000:00:05.0 ens5: interface_down: 1
...
[...]: ena 0000:00:05.0 ens5: Reading reg failed for timeout. expected: req id[10] offset[88] actual: req id[57015] offset[88]
[...]l: ena 0000:00:05.0 ens5: Reading reg failed for timeout. expected: req id[11] offset[8] actual: req id[57016] offset[88]
[...]: ena 0000:00:05.0 ens5: Reg read32 timeout occurred
[...]: ena 0000:00:05.0 ens5: Reading reg failed for timeout. expected: req id[1] offset[88] actual: req id[57006] offset[0]
[...]: ena 0000:00:05.0 ens5: Reading reg failed for timeout. expected: req id[2] offset[8] actual: req id[57007] offset[0]
[...]: ena 0000:00:05.0 ens5: Reg read32 timeout occurred
[...] ena 0000:00:05.0: Can not reset device
[...] ena 0000:00:05.0: Can not initialize device  
```

This happened with the 5.15.114 kernel driver in [drivers/net/ethernet/amazon/ena](https://elixir.bootlin.com/linux/v5.15.114/source/drivers/net/ethernet/amazon/ena). 
I understand that the in-tree ena driver and the out-of-tree ena driver(this repo) have diverged (discussed here https://github.com/amzn/amzn-drivers/issues/196).

Could you recommend using the driver from this repository over the in-tree kernel driver in regard to the issue mentioned above? More broadly, would you endorse this out-of-tree driver for its hardware support and stability?

Also, could you clarify the strategy behind the kernel's upstream driver? I'm leaning towards the out-of-tree option but am curious about the in-tree version's objectives.

Thanks
Vincent

**Comment by davidarinzon** [comment]
Hi @Vincinator  

Thank you for reaching out.
The issue that you're observing above is not necessarily related to the ena driver version that you're picking and on whether it's 
the in-tree or out-of-tree driver.

To investigate the above further, we recommend to open a ticket to AWS support in order for this particular issue to be investigated. In that ticket, please provide additional info such as when the issue happened roughly as well as instance IDs.

Regarding the policy and strategy, generally speaking, the out-of-tree github driver is the most updated version. The in-tree upstream driver is updated periodically and is catching up.
As different Linux OS distributions pick up or sync to the upstream Kernel, they occasionally pick updates for the in-tree upstream driver. This happens based on the OS distribution policy and timeline.

We recommend picking the updated and latest ena driver from github if that's possible.

Let us know if you have further questions. You're also welcome to reach out via Email to darinzon@amazon.com.

**Comment by Vincinator** [comment]
Thanks for the quick and thorough reply!
Will close this issue, and will reach out to you directly in case anything is left unclear. 

This has been of great help for me. 
Thank you
