### ISSUE TITLE
[Support]: ens5 selects TX queue N, but real number of TX queues is M

### ISSUE THREAD

**Issue by freeball155** [amzn/amzn-drivers#281]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
- [X] I have followed the [AWS official troubleshoot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).
- [X] I have followed the driver [readme](https://github.com/amzn/amzn-drivers) and [best practices](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst).

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

 6.2.0-1012-aws

### Custom Code

No

### OS Platform and Distribution

Linux  6.2.0-1012-aws #12-Ubuntu 
Instance type: c5n.large
AMI: aws-marketplace/ubuntu/images/hvm-ssd/ubuntu-lunar-23.04-amd64-server-20230725-e2e33685-9a6f-4cb6-ae4e-eb075484baed

### Support request

Hi.

I've noticed these messages in syslog:
Sep 22 07:40:15 ip-172-29-10-138 kernel: ens5 selects TX queue 2, but real number of TX queues is 2
Sep 22 07:40:17 ip-172-29-10-138 kernel: ens5 selects TX queue 2, but real number of TX queues is 2
Sep 22 07:40:22 ip-172-29-10-138 kernel: ens5 selects TX queue 2, but real number of TX queues is 2
Sep 22 07:40:30 ip-172-29-10-138 kernel: ens5 selects TX queue 2, but real number of TX queues is 2
Sep 22 07:40:46 ip-172-29-10-138 kernel: ens5 selects TX queue 2, but real number of TX queues is 2
Sep 22 07:41:18 ip-172-29-10-138 kernel: ens5 selects TX queue 2, but real number of TX queues is 2
Sep 22 07:43:29 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2
Sep 22 07:43:30 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2
Sep 22 07:43:32 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2
Sep 22 07:43:37 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2
Sep 22 07:43:45 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2
Sep 22 07:44:01 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2
Sep 22 07:44:33 ip-172-29-10-138 kernel: ens5 selects TX queue 3, but real number of TX queues is 2

How can I fix it?

ethtool -l ens5
Channel parameters for ens5:
Pre-set maximums:
RX:             n/a
TX:             n/a
Other:          n/a
Combined:       2
Current hardware settings:
RX:             n/a
TX:             n/a
Other:          n/a
Combined:       2

ethtool -i ens5
driver: ena
version: 6.2.0-1012-aws
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

ethtool -S ens5
NIC statistics:
     tx_timeout: 0
     suspend: 0
     resume: 0
     wd_expired: 0
     interface_up: 2
     interface_down: 1
     admin_q_pause: 0
     bw_in_allowance_exceeded: 0
     bw_out_allowance_exceeded: 0
     pps_allowance_exceeded: 0
     conntrack_allowance_exceeded: 0
     linklocal_allowance_exceeded: 0
     queue_0_tx_cnt: 477087
     queue_0_tx_bytes: 154433575
     queue_0_tx_queue_stop: 0
     queue_0_tx_queue_wakeup: 0
     queue_0_tx_dma_mapping_err: 0
     queue_0_tx_linearize: 0
     queue_0_tx_linearize_failed: 0
     queue_0_tx_napi_comp: 1277288
     queue_0_tx_tx_poll: 1277293
     queue_0_tx_doorbells: 472347
     queue_0_tx_prepare_ctx_err: 0
     queue_0_tx_bad_req_id: 0
     queue_0_tx_llq_buffer_copy: 118247
     queue_0_tx_missed_tx: 0
     queue_0_tx_unmask_interrupt: 1277288
     queue_0_rx_cnt: 854763
     queue_0_rx_bytes: 214892812
     queue_0_rx_rx_copybreak_pkt: 729203
     queue_0_rx_csum_good: 821918
     queue_0_rx_refil_partial: 0
     queue_0_rx_csum_bad: 0
     queue_0_rx_page_alloc_fail: 0
     queue_0_rx_skb_alloc_fail: 0
     queue_0_rx_dma_mapping_err: 0
     queue_0_rx_bad_desc_num: 0
     queue_0_rx_bad_req_id: 0
     queue_0_rx_empty_rx_ring: 0
     queue_0_rx_csum_unchecked: 26182
     queue_0_rx_xdp_aborted: 0
     queue_0_rx_xdp_drop: 0
     queue_0_rx_xdp_pass: 0
     queue_0_rx_xdp_tx: 0
     queue_0_rx_xdp_invalid: 0
     queue_0_rx_xdp_redirect: 0
     queue_1_tx_cnt: 437674
     queue_1_tx_bytes: 136123444
     queue_1_tx_queue_stop: 0
     queue_1_tx_queue_wakeup: 0
     queue_1_tx_dma_mapping_err: 0
     queue_1_tx_linearize: 0
     queue_1_tx_linearize_failed: 0
     queue_1_tx_napi_comp: 1776342
     queue_1_tx_tx_poll: 1776342
     queue_1_tx_doorbells: 437219
     queue_1_tx_prepare_ctx_err: 0
     queue_1_tx_bad_req_id: 0
     queue_1_tx_llq_buffer_copy: 97552
     queue_1_tx_missed_tx: 0
     queue_1_tx_unmask_interrupt: 1776342
     queue_1_rx_cnt: 1348013
     queue_1_rx_bytes: 104639036
     queue_1_rx_rx_copybreak_pkt: 1337471
     queue_1_rx_csum_good: 1348012
     queue_1_rx_refil_partial: 0
     queue_1_rx_csum_bad: 0
     queue_1_rx_page_alloc_fail: 0
     queue_1_rx_skb_alloc_fail: 0
     queue_1_rx_dma_mapping_err: 0
     queue_1_rx_bad_desc_num: 0
     queue_1_rx_bad_req_id: 0
     queue_1_rx_empty_rx_ring: 0
     queue_1_rx_csum_unchecked: 1
     queue_1_rx_xdp_aborted: 0
     queue_1_rx_xdp_drop: 0
     queue_1_rx_xdp_pass: 0
     queue_1_rx_xdp_tx: 0
     queue_1_rx_xdp_invalid: 0
     queue_1_rx_xdp_redirect: 0
     ena_admin_q_aborted_cmd: 0
     ena_admin_q_submitted_cmd: 49
     ena_admin_q_completed_cmd: 49
     ena_admin_q_out_of_space: 0
     ena_admin_q_no_completion: 0

**Comment by davidarinzon** [comment]
Hi @freeball155 

Thanks for reaching out.
This issue is addressed in version 2.9.1g which was recently released.
You're welcome to try it and let us know whether it resolves the issue/logs that you're seeing.

**Comment by freeball155** [comment]
Yes. With 2.9.1g errors are gone.
Thank you.
