### ISSUE TITLE
[Documentation]: Mapping of upstream kernel versions to ENA driver versions

### ISSUE THREAD

**Issue by stewartsmith** [amzn/amzn-drivers#283]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

ena_linux_2.9.1

### Documentation issue description

Documentation on the state of the ENA driver in the upstream Linux kernel, and how that relates to the driver trees here would be beneficial for Linux distributions.

Ideally, all bug fixes would go to the appropriate stable trees, and upstream Linux is up to date with ENA drivers.

### Contact Details

trawets@amazon.com

**Comment by ndagan** [comment]
Hi Stewart,

We are in an on-going process of aligning the ENA driver upstream version to the one available in Amazon drivers github.

Please reach out to me or darinzon@ internally for further information.

Thanks.
