### ISSUE TITLE
FreeBSD: missing TSO and RXCSUM support

### ISSUE THREAD

**Issue by kyenduri** [amzn/amzn-drivers#29]
I am running FreeBSD 11.1-RC2 #0 on an AWS r4.large instance and see the following in the 'options' field -

ena0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=422<TXCSUM,JUMBO_MTU,LRO>

I don't see TSO in the 'options' field. I see in the README file -
The ENA driver supports:
- TSO over IPv4/IPv6

Is this a device limitation or the FreeBSD ena driver limitation?

**Comment by semihalf-krawczyk-michal** [comment]
The FreeBSD driver have TSO support implemented, however the device on AWS isn't supporting it, yet.

**Comment by kyenduri** [comment]
Thanks! Do you know when we will get TSO support for the device in AWS?

**Comment by kyenduri** [comment]
Also, I see that there is no RXCSUM support. This is causing software LRO to be skipped. Specifically, tcp_lro_rx() is not called in the driver because of the lack of RXCSUM support. This could have a performance impact.

Is the lack of RXCSUM a device limitation?

**Comment by netanelbelgazal** [comment]
Rx checksum is currently unsupported by the device.
We plan to support it in future releases.

**Comment by gtzalik** [comment]
@kyenduri - As Michal and Netanel mentioned above, the ENA device is currently doesn't support Rx checksum and TSO. We do plan to add these features in the future but I don't have estimate time for releasing them now.
closing this issue. let me know if you need anything else.

**Comment by kyenduri** [comment]
Thanks!  I wanted to confirm this is not a FreeBSD driver specific issue and got the confirmation. Linux driver also has the same behavior.

**Comment by erenon** [comment]
Does the current AWS NIC support TSO now?

**Comment by akiyano** [comment]
Hi @erenon,
The ENA device currently does not support TSO.
