### ISSUE TITLE
[Documentation]: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html doesn't mention `phc_enable` module option

### ISSUE THREAD

**Issue by dwmw2** [amzn/amzn-drivers#304]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

HEAD

### Documentation issue description

Cutting this as an ENA driver bug because it shouldn't *need* documenting. It should Just Work by default.

And cutting it as a documentation bug because it's a failure of the "if it needs documenting, *fix* it first" tenet.

Please change the default for the `phc_enable` option to be enabled.

### Contact Details

dwmw@amazon.co.uk

**Comment by amitbern-aws** [comment]
Hi @dwmw2

1. In the same link you used (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) under **Requirements**, it is also mentioned to see driver prerequisites (https://github.com/amzn/amzn-drivers/tree/master/kernel/linux/ena#prerequisites).
Driver prerequisites holds all needed info to enable PHC, including module param, compilation and activation.

2. The need for PHC is often specific to certain applications, such as financial trading, where precise time synchronization is crucial. For general use cases, the benefits of PHC might not justify the potential overhead. Allowing users to enable PHC as needed provides flexibility without imposing unnecessary complexity on all users.
In addition, currently not all instances are compatible with PHC. Enabling it by default could lead to instability or unexpected behavior in systems where the device does not support PHC adequately. Ensuring stable and reliable network performance is a priority, and defaulting to PHC might jeopardize this for some configurations.

Thanks
