### ISSUE TITLE
[Support]: DPDK support for ENA 2.12.0

### ISSUE THREAD

**Issue by jain-rajat** [amzn/amzn-drivers#307]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
- [X] I have followed the [AWS official troubleshoot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).
- [X] I have followed the driver [readme](https://github.com/amzn/amzn-drivers) and [best practices](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst).

### Driver Type

DPDK PMD for Elastic Network Adapter (ENA)

### Driver Tag/Commit

master

### Custom Code

No

### OS Platform and Distribution

5.10.218-208.862.amzn2.aarch64

### Support request

In ReadMe, I found that the latest ENA driver compatibility is 2.8.0 for DPDK v23, 
And so I am not sure if it can be supported by ENA 2.12.0

### Contact Details

jain.rajat61@gmail.com

**Comment by amitbern-aws** [comment]
@jain-rajat
DPDK latest driver is 2.8.0
Linux latest driver is 2.12.1
Those are two different drivers.
Thanks
