### ISSUE TITLE
[Support]: Commit with changelog entries does not change actual code?

### ISSUE THREAD

**Issue by likewise** [amzn/amzn-drivers#309]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
- [X] I have followed the [AWS official troubleshoot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).
- [X] I have followed the driver [readme](https://github.com/amzn/amzn-drivers) and [best practices](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst).

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

x

### Custom Code

No

### OS Platform and Distribution

x

### Support request

The commit that adds these Changelog entries does not change any code? How can that be? It is confusing.

https://github.com/amzn/amzn-drivers/commit/e71f16153d383305ee657b0aa32da16919eaa880

## r2.12.3 release notes
** Bug fixes**
* Remove explicit numa specification for Linux
* Fix interrupt interval change flag override
* Prevent adaptive moderation override
* Free copybreak page if NUMA is incorrect

### Contact Details

leon@sidebranch.com

**Comment by akiyano** [comment]
Hi Leon,

Each time we add a new release to the driver, it includes a group of commits with code changes, and the last commit includes the update to driver version and release notes.
It makes sense to separate the release notes and driver version from actual code commits.
The commit message also states exactly what is done in the commit.

Sorry about your confusion
