### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by JamesBromberger** [amzn/amzn-drivers#4]
Rather than having to read the README for the version number, it would be nice to know it from the URL of the tarball from the download of a release. Its also a stable point release rather than a moving target. Please tag a release.

**Comment by AWSNB** [comment]
James, just a note that the team is looking into this, sorry for not updating you earlier

**Comment by alex-miro** [comment]
what commit ids do need to checkout version 1.0.0 ?

**Comment by zorikm** [comment]
b594ac1ea9e0c70e8e95803a0cfd9f5f06ac097e should get you ver. 1.0.0.
We do recommend to use the latest version though.
We'll tag releases to make it easier

**Comment by netanelbelgazal** [comment]
@JamesBromberger 
I tagged the last two version of ENA (1.1.2 and 1.1.3).
