### ISSUE TITLE
Release notes and stable version

### ISSUE THREAD

**Issue by piyush-kansal** [amzn/amzn-drivers#50]
Hi,

Could you please start adding release notes to the ENA driver releases so that one can make an informed decision about whether to upgrade to the latest releases or not?

Besides, adding a stable tag or something would also be of great help.

Thanks.

**Comment by netanelbelgazal** [comment]
Hi @piyush-kansal,

We already have release notes in the ENA driver.
Direct link: https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/RELEASENOTES.md

**Comment by piyush-kansal** [comment]
Oops. My bad. Thanks for your quick reply though.

Is it safe to assume that the most recent version of the drivee is also the most stable one?

**Comment by netanelbelgazal** [comment]
Yes,
All the releases in the Github are stable.
