### ISSUE TITLE
oracle uek kernel module build fails

### ISSUE THREAD

**Issue by cristiansavaro** [amzn/amzn-drivers#52]
can you make this module build on kernel-uek ?

**Comment by zorikm** [comment]
ENA is included in UEK Release 4 and also will be part of Release 5.

**Comment by cristiansavaro** [comment]
i need it for uek 3

**Comment by zorikm** [comment]
We are working on it. Will update you regarding expected delivery date.

**Comment by cristiansavaro** [comment]
thanks !

**Comment by zorikm** [comment]
Hello Cristian,
Apologies for delay.
We expect have a solution within a week.

**Comment by akiyano** [comment]
Hi @cristiansavaro,

A fix for this issue was released  here: https://github.com/amzn/amzn-drivers/commit/93897080ac55e51ed3f837ff1f056cca9d8b501c
Please fetch the latest version.

Regards,
Arthur

**Comment by cristiansavaro** [comment]
thanks. i will try it asap !
