### ISSUE TITLE
DRV_MODULE_VER_SUBMINOR not updated after ENA linux driver v1.5.1 released 

### ISSUE THREAD

**Issue by legopost** [amzn/amzn-drivers#58]
After ENA linux driver version 1.5.1 released DRV_MODULE_VER_SUBMINOR should be set to "1"

**Comment by legopost** [comment]
https://github.com/amzn/amzn-drivers/pull/59

**Comment by akiyano** [comment]
Hi @legopost,

The issue was fixed in the latest commit here https://github.com/amzn/amzn-drivers/commit/90a3a7e3dcf4782eb6ff5971755b1296c98a5029

Thanks for the pull request I applied your suggested changes.

Regards,
Arthur
