### ISSUE TITLE
cannot ena device speed with ethtool (eu-west)

### ISSUE THREAD

**Issue by sashas-lb** [amzn/amzn-drivers#61]
i`m running m4.16xlarge with ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126 (ami-1b791862) image. 
when running ethtool ens3 yields the following output:
Settings for ens3:
	Current message level: 0x000004e3 (1251)
			       drv probe ifup rx_err tx_err tx_done
	Link detected: yes

i.e. speed is not printed 

I had traced it to the following print (enabled via dyndebug)
echo "file ena_com.c line 796 +p" > /sys/kernel/debug/dynamic_debug/control
yields :
[  863.844540] ena: Feature 27 isn't supported
when running ethtool command.

It seems that ENA_ADMIN_LINK_CONFIG is not supported by the device.

dmesg during initialization:
[   10.828330] ena: Elastic Network Adapter (ENA) v1.3.0K
[   10.831006] ena 0000:00:03.0: Elastic Network Adapter (ENA) v1.3.0K
[   10.843325] ena: ena device version: 0.10
[   10.845477] ena: ena controller version: 0.0.1 implementation version 1
[   10.854098] AVX2 version of gcm_enc/dec engaged.
[   10.856801] AES CTR mode by8 optimization enabled
[   10.938797] ena 0000:00:03.0: creating 8 io queues. queue size: 1024
[   10.946848] ena 0000:00:03.0: Elastic Network Adapter (ENA) found at mem f3000000, mac addr 02:db:fc:5d:93:e8 Queues 8
[   10.953476] ena 0000:00:03.0 ens3: renamed from eth0

-------------------------------------------------------------------------------------------------------------------------
ethtool -i ens3
driver: ena
version: 1.3.0K
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

----------------------------------------------- lspci relevant lines---------------------------------------------------------
00:03.0 Ethernet controller: Device 1d0f:ec20
	Physical Slot: 3
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Region 0: Memory at f3000000 (32-bit, non-prefetchable) [size=16K]
	Capabilities: [70] Express (v2) Endpoint, MSI 00
		DevCap:	MaxPayload 256 bytes, PhantFunc 0, Latency L0s <1us, L1 <8us
			ExtTag- AttnBtn- AttnInd- PwrInd- RBE+ FLReset-
		DevCtl:	Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
			RlxdOrd+ ExtTag- PhantFunc- AuxPwr- NoSnoop+
			MaxPayload 128 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr- UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
		LnkCap:	Port #0, Speed unknown, Width x0, ASPM not supported, Exit Latency L0s <64ns, L1 <1us
			ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp-
		LnkCtl:	ASPM Disabled; RCB 64 bytes Disabled- CommClk-
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
		LnkSta:	Speed unknown, Width x0, TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Not Supported, TimeoutDis-, LTR-, OBFF Not Supported
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
		LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete-, EqualizationPhase1-
			 EqualizationPhase2-, EqualizationPhase3-, LinkEqualizationRequest-
	Capabilities: [b0] MSI-X: Enable+ Count=9 Masked-
		Vector table: BAR=0 offset=00002000
		PBA: BAR=0 offset=00003000
	Kernel driver in use: ena
	Kernel modules: ena

Is there any way to verify device is configured on 25G?

**Comment by zorikm** [comment]
@sashas-lb,
Thanks for your inquiry.  ENA device is actually a PCIe Virtual Function, and the "real" link is actually the shared physical network port.
The bandwidth services to each instance is limited per instance, and documented in our spec and technical documents, 
for example: 
https://aws.amazon.com/blogs/aws/the-floodgates-are-open-increased-network-bandwidth-for-ec2-instances
or
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/general-purpose-instances.html#general-purpose-network-performance​
The key point is: the bandwidth is per instance and not per ENI/ENA device.  So an instance with one ENI or multiple ENI will have same aggregate bandwidth. 
So putting an explicit number in the link-speed would likely be misleading as cannot represent the guaranteed bandwidth.
