### ISSUE TITLE
DPDK-pktgen : "PMD: Unsupported size of TX queue"

### ISSUE THREAD

**Issue by Luo-Liang** [amzn/amzn-drivers#76]
Hi!

I'm trying ENA with DPDK and pktgen-dpdk on EC2 c5.xlarge instance.

When running with `sudo ./pktgen -l 0-1 -n 2 - T -- -P -m "1.0"` I got an error `PMD: Unsupported size of TX queue (max size: 1024)`. It seems this error is thrown by ena, but I am unaware where the size of TX queue is set.

Please kindly let me know how to resolve this, or if I should ask around in another place.

Thanks!

**Comment by semihalf-krawczyk-michal** [comment]
Hi Liang,

the pktgen uses hardcoded Tx descriptors size. Please see file `pktgen-constants.h`.

For ENA maximum number of descriptors is 1024. The pktgen tries to use 2048 Tx descriptors. All you need to do is to change the `DEFAULT_TX_DESC` to 1024 in the file above and rebuild pktgen.

**Comment by Luo-Liang** [comment]
Thanks!
