### ISSUE TITLE
Feature request: XDP support

### ISSUE THREAD

**Issue by c4milo** [amzn/amzn-drivers#8]
are there any plans to support XDP? 

https://www.iovisor.org/technology/xdp

**Comment by zorikm** [comment]
Hi Camilo,
We do have plans to support XDP in future releases.
Still do not have exact dates.
Having said that, we definitely encourage community to contribute.

**Comment by tgraf** [comment]
> Having said that, we definitely encourage community to contribute.

How we can help? We are developing https://github.com/cilium/cilium and would love to contribute.

**Comment by borkmann** [comment]
@zorikm @netanelbelgazal Do you have any new updates or rough ETA by now for integrating XDP on ena?

**Comment by sbernard31** [comment]
Any news about **XDP** support ? 

Does it exist any alternative/workaround to be able to use **XDP** in AWS ? (maybe using `virtio-net` driver?)

**Comment by nafeabshara** [comment]
we actively working on this, top of priority stack

**Comment by dwmw2** [comment]
net-next just opened for submissions....

**Comment by gtzalik** [comment]
XDP support was added to v2.2 and to net-next.
Closing
