### ISSUE TITLE
Build on Amazon ECS-Optimized Amazon Linux AMI 2018.03.h of ENA Driver fails

### ISSUE THREAD

**Issue by danielvw2003** [amzn/amzn-drivers#88]
Building RPM for ENA Driver fails with :

error: line 32: Dependency tokens must begin with alpha-numeric, '_' or '/': BuildRequires:     %kernel_module_package_buildreqs

I have been unable create using the Makefile provided.

**Comment by akiyano** [comment]
Hi danielvw2003,

I've reproduced the issue.
I'll update you once I have a fix.

Thanks,
Arthur
