### ISSUE TITLE
ENA Driver 1.6.0 on AMI 2018.3 and  Amazon ECS-Optimized Amazon Linux AMI 2018.03.h

### ISSUE THREAD

**Issue by danielvw2003** [amzn/amzn-drivers#89]
The installation of the module causes Kernel crash at startup and gives error "Out of Tree Module Taints Kernel." 
Kernel version: 
4.14.72-68.55.amzn1.x86_64

**Comment by akiyano** [comment]
Hi danielvw2003,

How did you install the driver? 
looking at https://github.com/amzn/amzn-drivers/issues/88 the RPM installation currently doesn't work on this AMI.

Thanks,
Arthur

**Comment by danielvw2003** [comment]
I compiled it using make then replaced the old 1.5 driver and ran dracut to rebuild intramfs

**Comment by akiyano** [comment]
The message "Out of Tree Module Taints Kernel" is normal and you would see it no matter how you would install the driver (rpm, DKMS or like you did). It only means that the driver is an out-of-tree module that does not come with the kernel it is built against.

**Comment by danielvw2003** [comment]
For some reason though the kernel crashes immediately after loading it.
